"""fix: update SIIAU parser for new summer format and persist estatus field

Revision ID: 7f41bd0c207d
Revises: bc27db50f2c1
Create Date: 2026-05-27 10:41:16.345449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f41bd0c207d'
down_revision: Union[str, None] = 'bc27db50f2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seccion', sa.Column('est', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seccion', 'est')
    # ### end Alembic commands ###
