"""Initial migration

Revision ID: ef57b7e8867c
Revises: 
Create Date: 2026-02-14 23:08:45.922252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef57b7e8867c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('siiau_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendario_siiau_id'), 'calendario', ['siiau_id'], unique=True)
    op.create_table('centrouniversitario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('siiau_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centrouniversitario_name'), 'centrouniversitario', ['name'], unique=False)
    op.create_index(op.f('ix_centrouniversitario_siiau_id'), 'centrouniversitario', ['siiau_id'], unique=True)
    op.create_table('materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materia_clave'), 'materia', ['clave'], unique=True)
    op.create_index(op.f('ix_materia_name'), 'materia', ['name'], unique=False)
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesor_name'), 'profesor', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('edificio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['centro_id'], ['centrouniversitario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edificio_centro_id'), 'edificio', ['centro_id'], unique=False)
    op.create_index(op.f('ix_edificio_name'), 'edificio', ['name'], unique=False)
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_jti'), 'refreshtoken', ['jti'], unique=True)
    op.create_index(op.f('ix_refreshtoken_token_hash'), 'refreshtoken', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refreshtoken_user_id'), 'refreshtoken', ['user_id'], unique=False)
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nrc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.Column('cupos_disponibles', sa.Integer(), nullable=False),
    sa.Column('periodo_inicio', sa.DateTime(), nullable=True),
    sa.Column('periodo_fin', sa.DateTime(), nullable=True),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=True),
    sa.Column('calendario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendario_id'], ['calendario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['centro_id'], ['centrouniversitario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seccion_calendario_id'), 'seccion', ['calendario_id'], unique=False)
    op.create_index(op.f('ix_seccion_centro_id'), 'seccion', ['centro_id'], unique=False)
    op.create_index(op.f('ix_seccion_materia_id'), 'seccion', ['materia_id'], unique=False)
    op.create_index(op.f('ix_seccion_profesor_id'), 'seccion', ['profesor_id'], unique=False)
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('edificio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edificio_id'], ['edificio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aula_edificio_id'), 'aula', ['edificio_id'], unique=False)
    op.create_table('clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('dia', sa.Integer(), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aula_id'], ['aula.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_id'], ['seccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clase_aula_id'), 'clase', ['aula_id'], unique=False)
    op.create_index(op.f('ix_clase_seccion_id'), 'clase', ['seccion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clase_seccion_id'), table_name='clase')
    op.drop_index(op.f('ix_clase_aula_id'), table_name='clase')
    op.drop_table('clase')
    op.drop_index(op.f('ix_aula_edificio_id'), table_name='aula')
    op.drop_table('aula')
    op.drop_index(op.f('ix_seccion_profesor_id'), table_name='seccion')
    op.drop_index(op.f('ix_seccion_materia_id'), table_name='seccion')
    op.drop_index(op.f('ix_seccion_centro_id'), table_name='seccion')
    op.drop_index(op.f('ix_seccion_calendario_id'), table_name='seccion')
    op.drop_table('seccion')
    op.drop_index(op.f('ix_refreshtoken_user_id'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_token_hash'), table_name='refreshtoken')
    op.drop_index(op.f('ix_refreshtoken_jti'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_index(op.f('ix_edificio_name'), table_name='edificio')
    op.drop_index(op.f('ix_edificio_centro_id'), table_name='edificio')
    op.drop_table('edificio')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_profesor_name'), table_name='profesor')
    op.drop_table('profesor')
    op.drop_index(op.f('ix_materia_name'), table_name='materia')
    op.drop_index(op.f('ix_materia_clave'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_centrouniversitario_siiau_id'), table_name='centrouniversitario')
    op.drop_index(op.f('ix_centrouniversitario_name'), table_name='centrouniversitario')
    op.drop_table('centrouniversitario')
    op.drop_index(op.f('ix_calendario_siiau_id'), table_name='calendario')
    op.drop_table('calendario')
    # ### end Alembic commands ###
